"""Add attachment table

Backs the endpoints in docs/API.md §8. The original autogenerated revision was
committed with an empty `upgrade()`, so this table never existed in any migrated
database — the test suite only saw it because it built the schema from ORM
metadata instead of from migrations.

Revision ID: 99de55862c0e
Revises: 0006_audit_safeguard
Create Date: 2026-08-21 17:16:41.779910
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "99de55862c0e"
down_revision: str | None = "0006_audit_safeguard"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "attachment",
        sa.Column("id", sa.UUID(), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("ticket_id", sa.UUID(), sa.ForeignKey("ticket.id"), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        # Size is validated against APP_ATTACHMENT_MAX_BYTES before the row is
        # written; the CHECK is the backstop against a direct insert.
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("size >= 0", name="attachment_size_non_negative"),
    )
    # Mirrors ix_comment_ticket: fetch a ticket's attachments in order.
    op.create_index("ix_attachment_ticket", "attachment", ["ticket_id", "created_at"])


def downgrade() -> None:
    op.drop_index("ix_attachment_ticket", table_name="attachment")
    op.drop_table("attachment")
