import uuid
from datetime import datetime

from sqlalchemy import (
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    text,
)
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TimestampMixin, UUIDMixin
from .enums import Category, Priority, TicketStatus


class Ticket(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "ticket"

    customer_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("customer.id"), nullable=False)
    assignee_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("app_user.id"), nullable=True)
    subject: Mapped[str] = mapped_column(String, nullable=False)
    body: Mapped[str] = mapped_column(String, nullable=False)
    category: Mapped[Category] = mapped_column(nullable=False)
    priority: Mapped[Priority] = mapped_column(nullable=False)
    status: Mapped[TicketStatus] = mapped_column(default=TicketStatus.OPEN, nullable=False)
    deadline: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    escalation_level: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    sla_breached_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── SLA pause accounting (P16, spec05 §2) ────────────────────────────────
    # `deadline` above stays the frozen original promise (INV-1/INV-2).
    # `sla_due_at` is the current effective due time, recomputed at exactly one
    # moment: when the clock resumes. Materialized rather than computed on read
    # so the monitor's partial index still works.
    sla_due_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        # At insert, paused_seconds is 0, so INV-13 reduces to
        # `sla_due_at == deadline`. Defaulting to it is the definition rather
        # than a convenience, and it means no creation path can forget the
        # column and produce a ticket the monitor would never see.
        default=lambda ctx: ctx.get_current_parameters()["deadline"],
        nullable=False,
    )
    sla_paused_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    sla_paused_seconds: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    reopen_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # The policy this ticket's deadline was computed under (INV-15). Never
    # changes: no service exposes a write path and no repository UPDATE
    # includes it.
    sla_policy_version_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("sla_policy_version.id"), nullable=False
    )

    # Generated by PostgreSQL from (subject, body) — migration 0011. Never
    # written by the application, so it cannot drift from the text it indexes.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "setweight(to_tsvector('english', coalesce(subject, '')), 'A') || "
            "setweight(to_tsvector('english', coalesce(body, '')), 'B')",
            persisted=True,
        ),
        nullable=True,
    )

    __table_args__ = (
        CheckConstraint("escalation_level >= 0", name="ticket_escalation_level_check"),
        CheckConstraint(
            "resolved_at IS NULL OR status IN ('RESOLVED', 'CLOSED')",
            name="resolved_requires_status",
        ),
        CheckConstraint(
            "sla_breached_at IS NULL OR sla_breached_at >= sla_due_at",
            name="breached_only_when_past_due",
        ),
        CheckConstraint("sla_paused_seconds >= 0", name="sla_paused_seconds_non_negative"),
        CheckConstraint("reopen_count >= 0", name="reopen_count_non_negative"),
        # INV-14, enforced by the database rather than by convention.
        CheckConstraint(
            "(sla_paused_at IS NOT NULL) = (status = 'PENDING_CUSTOMER')",
            name="paused_iff_pending_customer",
        ),
        Index(
            "ix_ticket_sla_scan",
            "sla_due_at",
            postgresql_where=text(
                "sla_breached_at IS NULL "
                "AND status NOT IN ('RESOLVED', 'CLOSED', 'PENDING_CUSTOMER')"
            ),
        ),
        Index("ix_ticket_assignee_status", "assignee_id", "status"),
        Index("ix_ticket_customer", "customer_id", text("created_at DESC")),
    )
